apiVersion: batch/v1
kind: Job
metadata:
  name: train-nn
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: train-nn
          image: docker.io/ctvqfq/bunny_ai:classifier-1.0
          command: ["/bin/sh", "-c"]
          args: ["cd /develop/code/classifier/classifier; \
                  torchrun \
                  --nnodes 1 \
                  --nproc_per_node 2 \
                  --max_restarts 0 \
                  main.py \
                  --config configs/params.yaml \
                  --arch 0 \
                  --deploy 0 \
                  --test /develop/data/cifar/test \
                  --valid /develop/data/cifar/test \
                  --train /develop/data/cifar/train \
                  --results /develop/results/classifier"]
          resources:
            limits:
              memory: 40G
              cpu: 30
              nvidia.com/gpu: 2
            requests:
              memory: 40G
              cpu: 30
              nvidia.com/gpu: 2
          volumeMounts:
            - name: classifier-results
              mountPath: /develop/results
            - name: classifier-data
              mountPath: /develop/data
            - name: classifier-code
              mountPath: /develop/code
      volumes:
        - name: classifier-results
          persistentVolumeClaim:
            claimName: classifier-results

        - name: classifier-data
          persistentVolumeClaim:
            claimName: classifier-data

        - name: classifier-code
          persistentVolumeClaim:
            claimName: classifier-code

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                    - NVIDIA-GeForce-RTX-3090 
