apiVersion: batch/v1
kind: Job
metadata:
  name: train-nn
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: train-nn
          image: docker.io/ctvqfq/bunny_ai:classifier-1.1
          ports:
            - containerPort: 10044
          env:
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: NCCL_DEBUG
              value: INFO
          command: ["/bin/sh", "-c"]
          args: ["cd /develop/code/classifier/classifier; \
                  torchrun \
                  --nproc_per_node 2 \
                  main.py \
                  --config configs/params.yaml \
                  --arch 0 \
                  --deploy 0 \
                  --test /develop/data/cifar/test \
                  --valid /develop/data/cifar/test \
                  --train /develop/data/cifar/train \
                  --results /develop/results/classifier"]
          resources:
            limits:
              memory: 64G
              cpu: 32
              nvidia.com/gpu: 2
            requests:
              memory: 64G
              cpu: 32
              nvidia.com/gpu: 2
          volumeMounts:
            - name: classifier-results
              mountPath: /develop/results
            - name: classifier-data
              mountPath: /develop/data
            - name: classifier-code
              mountPath: /develop/code
      volumes:
        - name: classifier-results
          persistentVolumeClaim:
            claimName: classifier-results
        - name: classifier-data
          persistentVolumeClaim:
            claimName: classifier-data
        - name: classifier-code
          persistentVolumeClaim:
            claimName: classifier-code
